language: cpp

jobs:
  include:
    os: osx
    osx_image: xcode10
    
compiler:
  - clang++

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - cmake --build .
  
before_deploy:
  - echo $PWD

deploy:
  provider: releases
  token: $KEY
  file_glob: true
  file:
    - "*"
  on:
    branch: master
