language: cpp

jobs:
  include:
    os: osx
    osx_image: xcode10
    
compiler:
  - clang++

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - cmake --build .

deploy:
  provider: releases
  token: $KEY
  local_dir: bin
  cleanup: false
  on:
    branch: master
