language: cpp

jobs:
  include:
    os: osx
    osx_image: xcode10
    
compiler:
  - clang++

script:
  - mkdir build
  - cd build
  - cmake .. && cmake --build .
  - ls -lha

before_deploy:
  - echo $PWD
  - ls -lha
  - tar czf Morfogenesi.tar.gz .
  
deploy:
  provider: releases
  token: $KEY
  file_glob: true
  file:
    - "*"
  on:
    branch: master
