language: cpp

matrix:
  include:
    os: osx
    osx_image: xcode10
    
compiler:
  - clang++

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - cmake --build .

deploy:
  provider: releases
  api_key: "${KEY}"
  file: "bin/Morfogenesi.Main"
  skip_cleanup: true
  draft: true
