language: cpp

jobs:
  include:
    os: osx
    osx_image: xcode10
    
compiler:
  - clang++

script:
  - mkdir build
  - cd build
  - cmake .. && cmake --build .
  - tar czf Morfogenesi.tar.gz core
  - cd ..

deploy:
  skip_cleanup: true
  provider: releases
  token: $KEY
  file:
    - "./build/Morfogenesi.tar.gz"
  on:
    branch: master
